url: http://anxietyfreestats.com
baseurl: ""

# Site settings
title: Anxiety-Free Stats!
email: stats@seanho.com
description: "Statstical help for your dissertation"

# Team names, titles and social links
people:
- name: Dr. Howard Andersen
  pic: 1
  position: Statistical Consultant

- name: Dr. Sean Ho
  pic: 2
  position: Statistical Consultant
  social:
    - title: github
      url: https://github.com/seanho00
    - title: linkedin
      url: https://linkedin.com/seanho00

- name: Rob Matula
  pic: 3
  position: Statistical Consultant

# Build settings
markdown: kramdown
permalink: pretty
