remote_theme: SotiriosVrachas/jekyll-theme-startbootstrap-agency

title: Anxiety-Free Stats!
description: "Statstical help for your dissertation"
author: 'afs@seanho.com'

assets_path: 'assets/'

sass:
  style: compressed
