remote_theme: y7kim/agency-jekyll-theme

url: https://anxietyfreestats.github.io/
baseurl: ""

# Site settings
title: Anxiety-Free Stats!
email: stats@seanho.com
description: "Statstical help for your dissertation"

# Team names, titles and social links
people:
- name: Dr. Howard Andersen
  pic: generic.svg
  position: Statistical Consultant

- name: Dr. Sean Ho
  pic: seanho.png
  position: Statistical Consultant
  social:
    - title: github
      url: https://github.com/seanho00
    - title: linkedin
      url: https://linkedin.com/seanho00

- name: Rob Matula
  pic: rob.jpg
  position: Statistical Consultant

# Build settings
markdown: kramdown
permalink: pretty
