brand:
  name: Anxiety-Free Stats
menu-string: Menu

nav:
  - title: Services
    url: '#services'
  - title: About
    url: '#about'
  - title: Team
    url: '#team'
  - title: Contact
    url: '#contact'

copyright: '&copy; 2018 Anxiety-Free Stats'

social-buttons:
  - icon: fa-envelope
    url: mailto:afs@seanho.com
